Update master_achievo.yml

diff --git a/.github/workflows/master_achievo.yml b/.github/workflows/master_achievo.yml
--- a/.github/workflows/master_achievo.yml
+++ b/.github/workflows/master_achievo.yml
@@ -25,9 +25,14 @@ jobs:
       - name: Build Angular App
         run: npm run build -- --configuration production --base-href "/Achievo/"
 
-      - name: Deploy to GitHub Pages
-        uses: JamesIves/github-pages-deploy-action@v4
-        with:
-          branch: gh-pages
-          folder: dist/Achievo
-          clean: true
+      - name: DEBUG
+        run: ls -R dist || echo "dist folder not found"
+
+
+      #- name: Deploy to GitHub Pages
+        #uses: JamesIves/github-pages-deploy-action@v4
+        #with:
+          #branch: gh-pages
+          #folder: dist/Achievo
+          #clean: true
+
